project_id = "buoysrflkhemyterpamd"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.generate-seating]
    verify_jwt = false
  [functions.import-history]
    verify_jwt = false
  [functions.invite-user]
    verify_jwt = false
  [functions.seating-ai-assistant]
    verify_jwt = false
  [functions.external-api]
    verify_jwt = false
